version: "2"
services:
  consul:
    image: gliderlabs/consul-server
    command: -bootstrap
    ports:
      - "8500:8500"
  registrator:
    image: gliderlabs/registrator:master
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -retry-attempts 10 consul://consul:8500
  registry:
    image: registry:2
    ports:
      - "5000:5000"
  gocd-server:
    image: gocd/gocd-server:v20.4.0
    ports:
      - "8153:8153"
    volumes:
      - ./gocd-server/cruise-config.xml:/godata/config/cruise-config.xml
    user: root
  gocd-agent:
    image: gocd/gocd-agent-alpine-3.9:v20.4.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gocd-agent/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    environment:
      - GO_SERVER_URL=http://gocd-server:8153/go
      - AGENT_AUTO_REGISTER_KEY=f5a24b44-7b7d-4361-84da-3cd4dd958828
    links:
      - gocd-server
    user: root
